In [2]:
import numpy
import os
import cv2

In [9]:
im_g=cv2.imread("smallgray.png", 0)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [10]:
im_rbg=cv2.imread('smallgray.png',1)
im_rbg

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [11]:
cv2.imwrite('newsmallgray.png', im_rbg)

True

In [12]:
im_g[0:2,0:2]

array([[187, 158],
       [198, 125]], dtype=uint8)

In [14]:
im_g.shape

(3, 5)

In [17]:
for i in im_g.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [18]:
ims=numpy.hstack((im_g,im_g))

In [23]:
ims=numpy.vstack((im_g,im_g))
ims

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)